name: S3 Deployment
on:
  push:
    branches: [ main ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.12.0]
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
    - name: Checkout
      uses: actions/checkout@v2
      with:
          ref: ${{ github.ref }}
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install
      run: npm install
          env:
              NODE_AUTH_TOKEN: ${{ secrets.DEV_OPS_TOKEN_READ_PACKAGES }}
    - name: Build
      run: npm run build --if-present
    - name: Deploy to S3
      run: |
          aws s3 cp "index.min.js" "s3://sakaba.link/index.min.js"
          aws s3 cp "index.html" "s3://sakaba.link/index.html"
          aws s3 cp "main.css" "s3://sakaba.link/main.css"
          aws s3 cp "robots.txt" "s3://sakaba.link/robots.txt"
          aws s3 cp "sitemap.xml" "s3://sakaba.link/sitemap.xml"
          aws s3 cp "favicon.ico" "s3://sakaba.link/favicon.ico"
    - name: CloudFront Invalidation
      run: aws cloudfront create-invalidation --distribution-id ${{ secrets.CF_DISTRIBUTION_ID }} --paths "/*"
