name: GCS Deployment
on:
  push:
    branches: [ main ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    strategy:
      matrix:
        node-version: [20]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install pnpm
      uses: pnpm/action-setup@v3
      with:
        version: 8
        run_install: false
    - name: Get pnpm store directory
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
      env:
          NODE_AUTH_TOKEN: ${{ secrets.DEV_OPS_TOKEN_READ_PACKAGES }}
    - name: Setup pnpm cache
      uses: actions/cache@v4
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: 'Authenticate GCP'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ secrets.SERVICE_ACCOUNT }}
    - name: 'Setup Google Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'
      with:
        version: '>= 379.0.0'
    - name: Install dependencies
      run: pnpm install
      env:
          NODE_AUTH_TOKEN: ${{ secrets.DEV_OPS_TOKEN_READ_PACKAGES }}
    - name: Build
      run: pnpm run build
    - name: Deploy to GCS
      run: |
          gsutil cp index.min.js gs://sakabas.com/
          gsutil cp index.html gs://sakabas.com/
          gsutil cp main.css gs://sakabas.com/
          gsutil cp robots.txt gs://sakabas.com/
          gsutil cp sitemap.xml gs://sakabas.com/
          gsutil cp favicon.ico gs://sakabas.com/
          gsutil setmeta -r -h "Cache-Control: no-store, max-age=864000" gs://sakabas.com
