name: GCS Deployment
on:
  push:
    branches: [ main ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.3.0]
    steps:
    - name: Configure GCP Credentials
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
          service_account_key: ${{ secrets.GCS_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT }}
          export_default_credentials: true
    - name: Checkout
      uses: actions/checkout@v3
      with:
          ref: ${{ github.ref }}
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install
      run: npm install
      env:
          NODE_AUTH_TOKEN: ${{ secrets.DEV_OPS_TOKEN_READ_PACKAGES }}
    - name: Build
      run: npm run build --if-present
    - name: Deploy to GCS
      run: |
          gsutil cp index.min.js gs://ramen-mania.net/
          gsutil cp index.html gs://ramen-mania.net/
          gsutil cp main.css gs://ramen-mania.net/
          gsutil cp robots.txt gs://ramen-mania.net/
          gsutil cp sitemap.xml gs://ramen-mania.net/
          gsutil cp favicon.ico gs://ramen-mania.net/
