name: GCS Deployment
on:
  push:
    branches: [ main ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    strategy:
      matrix:
        node-version: [18.3.0]
    steps:
    - uses: actions/checkout@v3
    - name: 'Authenticate GCP'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ secrets.SERVICE_ACCOUNT }}
    - name: 'Setup Google Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'
      with:
        version: '>= 379.0.0'
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install
      run: npm install
      env:
          NODE_AUTH_TOKEN: ${{ secrets.DEV_OPS_TOKEN_READ_PACKAGES }}
    - name: Build
      run: npm run build --if-present
    - name: Deploy to GCS
      run: |
          gsutil cp index.min.js gs://ramen-mania.net/
          gsutil cp index.html gs://ramen-mania.net/
          gsutil cp main.css gs://ramen-mania.net/
          gsutil cp robots.txt gs://ramen-mania.net/
          gsutil cp sitemap.xml gs://ramen-mania.net/
          gsutil cp favicon.ico gs://ramen-mania.net/
